[build]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"

# [[redirects]]
# All redirections are handle in folder docs/.vurpress/public/_redirects file

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
