version: 2
jobs:
  build:
    working_directory: ~/docs
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn
      - save_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn docs:build
workflows:
  version: 2
  test:
    jobs:
      - build
